### ISSUE TITLE
Inconsistent coloring for "cancel"

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/user-management-page#7]
Everywhere else, the affirmative button is color coded and the "cancel" button is plain. For example, 
![DeepinScreenshot_select-area_20200403163640](https://user-images.githubusercontent.com/4982789/78407058-919bbb00-75c9-11ea-8fa6-c07371a30797.png)

However, in the token generation page, it is flipped:

![DeepinScreenshot_select-area_20200403163824](https://user-images.githubusercontent.com/4982789/78407084-9e201380-75c9-11ea-88b7-4fc478b4c375.png)

**Comment by umesh-timalsina** [comment]
![image](https://user-images.githubusercontent.com/11476842/78407488-944ae000-75ca-11ea-88c3-3e2585fa2575.png)

A similar style should be followed.

**Comment by umesh-timalsina** [comment]
#7 and #8 could be fixed together by using `<LoginField>` Component instead of using our own custom HTML in tokens Modal.

**Comment by umesh-timalsina** [comment]
A page should have a `state` rather than a widget. This is consistent with the design of the other pages in user-management-page.
